{"level":"ERROR","timestamps":"25 Aug 2025 22:27:53","caller":"logger/logger.go:91","message":"Failed to ping DB","error":"pq: password authentication failed for user \"root\"","trace":"blog_app/utils/logger.Error\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/utils/logger/logger.go:91\nblog_app/db.Init\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/db/db.go:46\nmain.main\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/server.go:27\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:283"}
{"level":"ERROR","timestamps":"25 Aug 2025 22:27:53","caller":"logger/logger.go:91","message":"APP_ERROR: Database initialization failed","error":"pq: password authentication failed for user \"root\"","trace":"blog_app/utils/logger.Error\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/utils/logger/logger.go:91\nmain.main\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/server.go:28\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:283"}
{"level":"ERROR","timestamps":"25 Aug 2025 22:42:01","caller":"logger/logger.go:91","message":"Failed to ping DB","error":"pq: password authentication failed for user \"root\"","trace":"blog_app/utils/logger.Error\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/utils/logger/logger.go:91\nblog_app/db.Init\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/db/db.go:46\nmain.main\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/server.go:27\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:283"}
{"level":"ERROR","timestamps":"25 Aug 2025 22:42:01","caller":"logger/logger.go:91","message":"APP_ERROR: Database initialization failed","error":"pq: password authentication failed for user \"root\"","trace":"blog_app/utils/logger.Error\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/utils/logger/logger.go:91\nmain.main\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/server.go:28\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:283"}
{"level":"ERROR","timestamps":"26 Aug 2025 00:59:27","caller":"logger/logger.go:91","message":"Failed to ping DB","error":"pq: password authentication failed for user \"root\"","trace":"blog_app/utils/logger.Error\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/utils/logger/logger.go:91\nblog_app/db.Init\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/db/db.go:46\nmain.main\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/server.go:27\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:283"}
{"level":"ERROR","timestamps":"26 Aug 2025 00:59:27","caller":"logger/logger.go:91","message":"APP_ERROR: Database initialization failed","error":"pq: password authentication failed for user \"root\"","trace":"blog_app/utils/logger.Error\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/utils/logger/logger.go:91\nmain.main\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/server.go:28\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:283"}
{"level":"ERROR","timestamps":"26 Aug 2025 01:01:31","caller":"logger/logger.go:91","message":"Failed to ping DB","error":"pq: password authentication failed for user \"root\"","trace":"blog_app/utils/logger.Error\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/utils/logger/logger.go:91\nblog_app/db.Init\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/db/db.go:46\nmain.main\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/server.go:27\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:283"}
{"level":"ERROR","timestamps":"26 Aug 2025 01:01:31","caller":"logger/logger.go:91","message":"APP_ERROR: Database initialization failed","error":"pq: password authentication failed for user \"root\"","trace":"blog_app/utils/logger.Error\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/utils/logger/logger.go:91\nmain.main\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/server.go:28\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:283"}
{"level":"ERROR","timestamps":"26 Aug 2025 01:08:21","caller":"logger/logger.go:91","message":"Failed to ping DB","error":"pq: password authentication failed for user \"root\"","trace":"blog_app/utils/logger.Error\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/utils/logger/logger.go:91\nblog_app/db.Init\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/db/db.go:46\nmain.main\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/server.go:27\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:283"}
{"level":"ERROR","timestamps":"26 Aug 2025 01:08:21","caller":"logger/logger.go:91","message":"APP_ERROR: Database initialization failed","error":"pq: password authentication failed for user \"root\"","trace":"blog_app/utils/logger.Error\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/utils/logger/logger.go:91\nmain.main\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/server.go:28\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:283"}
{"level":"ERROR","timestamps":"26 Aug 2025 01:10:29","caller":"logger/logger.go:91","message":"Failed to ping DB","error":"pq: password authentication failed for user \"postgres\"","trace":"blog_app/utils/logger.Error\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/utils/logger/logger.go:91\nblog_app/db.Init\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/db/db.go:46\nmain.main\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/server.go:27\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:283"}
{"level":"ERROR","timestamps":"26 Aug 2025 01:10:29","caller":"logger/logger.go:91","message":"APP_ERROR: Database initialization failed","error":"pq: password authentication failed for user \"postgres\"","trace":"blog_app/utils/logger.Error\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/utils/logger/logger.go:91\nmain.main\n\tC:/Users/PKHOLIYA/OneDrive - Capgemini/Desktop/____personal_Work/blog_app/server.go:28\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:283"}
